### ISSUE TITLE
[Tracker] Porting to 4.0 and improving for 4.0

### ISSUE THREAD

**Issue by clayjohn** [godotengine/tps-demo#162]
This tracker is for changes that need to be made for the TPS demo to be fully "ported" to Godot 4.0. It includes bugs that are present in the 4.0-dev branch and features we would like to see included in the full release of the demo.

### Bugs 
(Most reported by Calinou [here](https://github.com/godotengine/tps-demo/pull/161#pullrequestreview-1296615851))

- [ ] The flying forklift doesn't move in the air, while it's supposed to circle the area.
- [ ] The crosshair when aiming isn't correctly scaled (check TextureRect scale mode property).
- [ ] Some level UVs appear broken due to LOD generation, though it's not too noticeable in most areas.
- [ ] Key inputs in the input map should use physical key inputs, to allow for WASD controls to work out of the box on non-QWERTY keyboard layouts. This was done in the 3.x version.
- [ ] The stretch mode project setting should be changed to canvas_items (equivalent to 2d in 3.x).

### Enhancements
- [ ] GI Source: Lightmaps + ReflectionProbes (fast); static VoxelGI (medium); SDFGI + SSIL (high quality)
- [ ] Occlusion Culling

**Comment by clayjohn** [comment]
I have made most of the above changes in a WIP local commit. Will make a PR tomorrow
